# Generated by Django 3.2.16 on 2022-11-22 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='like_recipe',
            field=models.ManyToManyField(blank=True, default=None, related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
