# Generated by Django 3.2.16 on 2022-12-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_newsletterusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUsers',
            new_name='NewsletterUser',
        ),
    ]
